// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StowellCoAPI.DTO;

[Table("HardWareInventory")]
public partial class HardWareInventory
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("CompanyID")]
    [StringLength(200)]
    [Unicode(false)]
    public string CompanyId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DeviceName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DeviceType { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DeviceModel { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Department { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string User { get; set; }

    public bool IsPersonal { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LocalAdmin { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("DeviceID")]
    [StringLength(500)]
    [Unicode(false)]
    public string DeviceId { get; set; }

    [Column("ProductID")]
    [StringLength(500)]
    [Unicode(false)]
    public string ProductId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Serial { get; set; }

    [Column("MACAddress")]
    [StringLength(100)]
    [Unicode(false)]
    public string Macaddress { get; set; }

    [Column("IPAddress")]
    [StringLength(100)]
    [Unicode(false)]
    public string Ipaddress { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Processor { get; set; }

    [Column("RAM")]
    [StringLength(100)]
    [Unicode(false)]
    public string Ram { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OperatingSystem { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Version { get; set; }

    public bool Sentinel { get; set; }

    public bool GoToAssist { get; set; }

    public bool Office365 { get; set; }

    public bool AdobeViewer { get; set; }

    [Column("VDISoftware")]
    public bool Vdisoftware { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ModifiedBy { get; set; }
}