// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using StowellCoAPI.DTO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace StowellCoAPI.DTO
{
    public partial interface IStowellCoContextProcedures
    {
        Task<int> usp_HardWareInventory_DeleteAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_HardWareInventory_InsertAsync(int? ID, string CompanyID, string DeviceName, string DeviceType, string DeviceModel, string Department, string User, bool? IsPersonal, string LocalAdmin, string Password, string DeviceID, string ProductID, string Serial, string MACAddress, string IPAddress, string Processor, string RAM, string OperatingSystem, string Version, bool? Sentinel, bool? GoToAssist, bool? Office365, bool? AdobeViewer, bool? VDISoftware, string ModifiedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_HardWareInventory_SelectResult>> usp_HardWareInventory_SelectAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_HardWareInventory_UpdateAsync(int? ID, string CompanyID, string DeviceName, string DeviceType, string DeviceModel, string Department, string User, bool? IsPersonal, string LocalAdmin, string Password, string DeviceID, string ProductID, string Serial, string MACAddress, string IPAddress, string Processor, string RAM, string OperatingSystem, string Version, bool? Sentinel, bool? GoToAssist, bool? Office365, bool? AdobeViewer, bool? VDISoftware, string ModifiedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_NewUserRequest_DeleteAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_NewUserRequest_InsertAsync(string FirstName, string MiddleName, string LastName, string Suffix, string Address, string Address2, string City, string State, string Zip, string Phone, string Email, DateTime? HireDate, DateTime? StartDate, string Branch, string Title, string OfficePhone, bool? CompanyEmail, bool? Sage100, bool? NewLaptop, string NewLaptopName, bool? VDIVirtualDesktop, bool? SharedMailBoxAccess, string SharedMailBox1, string SharedMailBox2, string SharedMailBox3, string SharedMailBox4, string SharedMailBox5, bool? PDFViewer, string ModifiedBy, OutputParameter<int?> NewID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_NewUserRequest_SelectResult>> usp_NewUserRequest_SelectAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_NewUserRequest_UpdateAsync(int? ID, string FirstName, string MiddleName, string LastName, string Suffix, string Address, string Address2, string City, string State, string Zip, string Phone, string Email, DateTime? HireDate, DateTime? StartDate, string Branch, string Title, string OfficePhone, bool? CompanyEmail, bool? Sage100, bool? NewLaptop, string NewLaptopName, bool? VDIVirtualDesktop, bool? SharedMailBoxAccess, string SharedMailBox1, string SharedMailBox2, string SharedMailBox3, string SharedMailBox4, string SharedMailBox5, bool? PDFViewer, string ModifiedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
