// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StowellCoAPI.DTO;

[Table("NewUserRequest")]
public partial class NewUserRequest
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MiddleName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Suffix { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Address2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string State { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Zip { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "date")]
    public DateTime? HireDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Branch { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string OfficePhone { get; set; }

    public bool? CompanyEmail { get; set; }

    public bool? Sage100 { get; set; }

    public bool? NewLaptop { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string NewLaptopName { get; set; }

    [Column("VDIVirtualDesktop")]
    public bool? VdivirtualDesktop { get; set; }

    public bool? SharedMailBoxAccess { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SharedMailBox1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SharedMailBox2 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SharedMailBox3 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SharedMailBox4 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SharedMailBox5 { get; set; }

    [Column("PDFViewer")]
    public bool? Pdfviewer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ModifiedBy { get; set; }
}