// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StowellCoAPI.DTO;

public partial class StowellCoContext : DbContext
{
    public StowellCoContext(DbContextOptions<StowellCoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HardWareInventory> HardWareInventories { get; set; }

    public virtual DbSet<NewUserRequest> NewUserRequests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HardWareInventory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_HardWareInventory_ID");

            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<NewUserRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_NewUserRequest_ID");

            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}