// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace StowellCoAPI.DTO
{
    public partial class usp_HardWareInventory_SelectResult
    {
        public int ID { get; set; }
        public string CompanyID { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public string DeviceModel { get; set; }
        public string Department { get; set; }
        public string User { get; set; }
        public bool IsPersonal { get; set; }
        public string LocalAdmin { get; set; }
        public string Password { get; set; }
        public string DeviceID { get; set; }
        public string ProductID { get; set; }
        public string Serial { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string OperatingSystem { get; set; }
        public string Version { get; set; }
        public bool Sentinel { get; set; }
        public bool GoToAssist { get; set; }
        public bool Office365 { get; set; }
        public bool AdobeViewer { get; set; }
        public bool VDISoftware { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
