// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace StowellCoAPI.DTO
{
    public partial class usp_NewUserRequest_SelectResult
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? StartDate { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
        public string OfficePhone { get; set; }
        public bool? CompanyEmail { get; set; }
        public bool? Sage100 { get; set; }
        public bool? NewLaptop { get; set; }
        public string NewLaptopName { get; set; }
        public bool? VDIVirtualDesktop { get; set; }
        public bool? SharedMailBoxAccess { get; set; }
        public string SharedMailBox1 { get; set; }
        public string SharedMailBox2 { get; set; }
        public string SharedMailBox3 { get; set; }
        public string SharedMailBox4 { get; set; }
        public string SharedMailBox5 { get; set; }
        public bool? PDFViewer { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
